version: '3'

services:
  foresty-app:
    container_name: foresty-app
    image: foresty-app
    restart: always
    build: .
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/foresty
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: jakhonLovesHealing@99
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foresty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jakhonLovesHealing@99
    volumes:
      - db_data:/var/lib/postgresql/data/